name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./zadanie1
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache:latest
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache:latest,mode=max

    - name: Scan image for CVEs
      uses: aquasecurity/trivy-action@0.13.1
      with:
        image-ref: ghcr.io/${{ github.repository }}:latest
        ignore-unfixed: true
        severity: CRITICAL,HIGH

